/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as outerbaseNavHeaderLocalRouteImport } from './app/(outerbase)/nav-header-local'
import { Route as PlaygroundClientIndexRouteImport } from './app/playground/client/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const outerbaseNavHeaderLocalRoute = outerbaseNavHeaderLocalRouteImport.update({
  id: '/(outerbase)/nav-header-local',
  path: '/nav-header-local',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundClientIndexRoute = PlaygroundClientIndexRouteImport.update({
  id: '/playground/client/',
  path: '/playground/client/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nav-header-local': typeof outerbaseNavHeaderLocalRoute
  '/playground/client': typeof PlaygroundClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nav-header-local': typeof outerbaseNavHeaderLocalRoute
  '/playground/client': typeof PlaygroundClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(outerbase)/nav-header-local': typeof outerbaseNavHeaderLocalRoute
  '/playground/client/': typeof PlaygroundClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nav-header-local' | '/playground/client'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nav-header-local' | '/playground/client'
  id: '__root__' | '/' | '/(outerbase)/nav-header-local' | '/playground/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  outerbaseNavHeaderLocalRoute: typeof outerbaseNavHeaderLocalRoute
  PlaygroundClientIndexRoute: typeof PlaygroundClientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(outerbase)/nav-header-local': {
      id: '/(outerbase)/nav-header-local'
      path: '/nav-header-local'
      fullPath: '/nav-header-local'
      preLoaderRoute: typeof outerbaseNavHeaderLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/client/': {
      id: '/playground/client/'
      path: '/playground/client'
      fullPath: '/playground/client'
      preLoaderRoute: typeof PlaygroundClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  outerbaseNavHeaderLocalRoute: outerbaseNavHeaderLocalRoute,
  PlaygroundClientIndexRoute: PlaygroundClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
